# Generated by Django 2.2 on 2020-10-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20201027_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='txt',
        ),
    ]
