# Generated by Django 2.2.5 on 2020-10-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='count',
        ),
    ]
