# Generated by Django 2.2 on 2020-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cat", "0002_remove_cat_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
