# Generated by Django 2.2.5 on 2020-10-02 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="main",
            name="abouttxt",
        ),
        migrations.RemoveField(
            model_name="main",
            name="fb",
        ),
        migrations.RemoveField(
            model_name="main",
            name="link",
        ),
        migrations.RemoveField(
            model_name="main",
            name="picname",
        ),
        migrations.RemoveField(
            model_name="main",
            name="picname2",
        ),
        migrations.RemoveField(
            model_name="main",
            name="picurl",
        ),
        migrations.RemoveField(
            model_name="main",
            name="picurl2",
        ),
        migrations.RemoveField(
            model_name="main",
            name="set_name",
        ),
        migrations.RemoveField(
            model_name="main",
            name="tell",
        ),
        migrations.RemoveField(
            model_name="main",
            name="tw",
        ),
        migrations.RemoveField(
            model_name="main",
            name="yt",
        ),
    ]
