# Generated by Django 2.2 on 2020-10-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="ip",
            field=models.TextField(default=""),
        ),
    ]
